apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-example-deployment
  labels:
    app.kubernetes.io/name: flask-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-example
    spec:
      containers:
      - name: flask
        image: flask-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-example-service
  labels:
    app.kubernetes.io/name: flask-example
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: flask-example
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000